services:
  application:
    image: ${IMAGE_URL} # Image to be used

    container_name: app-${SERVICE} # Name for local container management
    user: "0:0"
    environment: # Varibles are delared in .env file.
      - TZ=${TZ}
      - VIKUNJA_SERVICE_PUBLICURL=${VIKUNJA_SERVICE_PUBLICURL}
      - VIKUNJA_DATABASE_PATH=${VIKUNJA_DATABASE_PATH}
    labels:
      - docktail.service.enable=true
      - docktail.service.name=${SERVICE}
      - docktail.service.port=${SERVICE_PORT}
      - docktail.service.service-port=443
    volumes:
      - /srv/appdata/${SERVICE}/files:/app/vikunja/files
      - /srv/appdata/${SERVICE}/db:/db
    restart: always