configs:
  ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:80"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:    
  application:
    image: ${IMAGE_URL} # Image to be used
    network_mode: service:tailscale # Sidecar configuration to route ${SERVICE} through Tailscale
    container_name: app-${SERVICE} # Name for local container management
    environment:
      - GOTIFY_DEFAULTUSER_PASS=admin
    labels:
      - docktail.service.enable=true
      - docktail.service.name=${SERVICE}
      - docktail.service.port=${SERVICE_PORT}
      - docktail.service.service-port=443
    volumes:
      - /srv/appdata/${SERVICE}/data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"] # Check if ${SERVICE} process is running
      interval: 1m # How often to perform the check
      timeout: 10s # Time to wait for the check to succeed
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 30s # Time to wait before starting health checks
    restart: always
