configs:
  ts-serve:
    content: |
      {"TCP":{"444":{"HTTPS":true}},
      "Web":{"$${TS_CERT_DOMAIN}:444":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:80"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:444":false}}

services:
  application:
    image: ${IMAGE_URL} # Image to be used

    container_name: app-${SERVICE} # Name for local container management
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - GROCY_CURRENCY=GBP
    labels:
      - docktail.service.enable=true
      - docktail.service.name=${SERVICE}
      - docktail.service.port=${SERVICE_PORT}
      - docktail.service.service-port=443
    volumes:
      - /srv/appdata/${SERVICE}/config:/config
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: always
