services:  
  application:
    image: ${IMAGE_URL} # Image to be used

    container_name: app-${SERVICE} # Name for local container management
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=homepage.${TAILNET_NAME}.ts.net
    labels:
      - docktail.service.enable=true
      - docktail.service.name=${SERVICE}
      - docktail.service.port=${SERVICE_PORT}
      - docktail.service.service-port=443
    volumes:
      - /srv/appdata/${SERVICE}/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    healthcheck:
      test: ["CMD", "pgrep", "-f", "next-server"] # Check if ${SERVICE} process is running
      interval: 1m # How often to perform the check
      timeout: 10s # Time to wait for the check to succeed
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 30s # Time to wait before starting health checks
    restart: always
