configs:
  ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:3000"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:
  application:
    image: ${IMAGE_URL} # Image to be used

    container_name: app-${SERVICE} # Name for local container management
    environment:
      - HOST_DATA_DIR=/app/data
    labels:
      - docktail.service.enable=true
      - docktail.service.name=${SERVICE}
      - docktail.service.port=${SERVICE_PORT}
      - docktail.service.service-port=443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/appdata/${SERVICE}/data:/app/data # Data directory for Dockhand - you may need to change the path
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://127.0.0.1:41234/healthz"] # Check if ${SERVICE} is responding
      interval: 1m # How often to perform the check
      timeout: 10s # Time to wait for the check to succeed
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 30s # Time to wait before starting health checks
    restart: always
