services:
  application:
    image: ${IMAGE_URL}
    container_name: app-${SERVICE}
    depends_on:
      db:
        condition: service_started
      broker:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost"] # Check if ${SERVICE} process is running
      interval: 1m # How often to perform the check
      timeout: 10s # Time to wait for the check to succeed
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 30s # Time to wait before starting health checks
    restart: always
    volumes:
      - /srv/appdata/${SERVICE}/data:/usr/src/paperless/data
      - /srv/appdata/${SERVICE}/media:/usr/src/paperless/media
      - /srv/appdata/${SERVICE}/export:/usr/src/paperless/export
      - /srv/appdata/${SERVICE}/consume:/usr/src/paperless/consume
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - PAPERLESS_TIME_ZONE=${PAPERLESS_TIME_ZONE}
      - PAPERLESS_OCR_LANGUAGE=${PAPERLESS_OCR_LANGUAGE}
      - PAPERLESS_SECRET_KEY=${PAPERLESS_SECRET_KEY}
      - PAPERLESS_PORT=80
      - PAPERLESS_PROXY_SSL_HEADER=["HTTP_X_FORWARDED_PROTO", "https"]
      - PAPERLESS_ADMIN_USER=${PAPERLESS_ADMIN_USER}
      - PAPERLESS_ADMIN_PASSWORD=${PAPERLESS_ADMIN_PASSWORD}
      - PAPERLESS_REDIS=redis://broker:6379
      - PAPERLESS_DBHOST=db
    labels:
      - docktail.service.enable=true
      - docktail.service.name=${SERVICE}
      - docktail.service.port=${SERVICE_PORT}
      - docktail.service.service-port=443

  db:
    image: docker.io/library/postgres:18
    container_name: app-${SERVICE}-db # Name for local container management
    restart: always
    volumes:
      - ./${SERVICE}-data/pgdata:/var/lib/postgresql
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - POSTGRES_DB=paperless
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  broker:
    image: docker.io/library/redis:8
    container_name: app-${SERVICE}-broker # Name for local container management
    restart: always
    volumes:
      - /srv/appdata/${SERVICE}/redisdata:/data
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
