services:
  # ${SERVICE}
  application:
    image: ${IMAGE_URL} # Image to be used
    network_mode: service:tailscale # Sidecar configuration to route ${SERVICE} through Tailscale
    container_name: app-${SERVICE} # Name for local container management
    environment:
      PORT: 45876
      LISTEN: 45876
      KEY: ${KEY}
      TOKEN: ${TOKEN}
      HUB_URL: ${HUB_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Read-only access to the docker.sock
      - /srv/appdata/${SERVICE}/data:/var/lib/beszel-agent
    labels:
      - docktail.service.enable=true
      - docktail.service.name=${SERVICE}
      - docktail.service.port=${SERVICE_PORT}
      - docktail.service.service-port=443
    depends_on:
      tailscale:
        condition: service_healthy
    healthcheck:
      test: ['CMD', '/agent', 'health'] # Check if Beszel Agent is running and accessible
      interval: 1m # How often to perform the check
      timeout: 10s # Time to wait for the check to succeed
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 30s # Time to wait before starting health checks
    restart: always
