services:
  application:
    image: ${IMAGE_URL}
    container_name: app-${SERVICE}
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    volumes:
      - /srv/appdata/${SERVICE}trainingData:/usr/share/tessdata
      - /srv/appdata/${SERVICE}extraConfigs:/configs
#      - /srv/appdata/${SERVICE}customFiles:/customFiles/ # May be enabled if desired
#      - /srv/appdata/${SERVICE}logs:/logs/ # May be enabled if desired
    labels:
      - docktail.service.enable=true
      - docktail.service.name=${SERVICE}
      - docktail.service.port=${SERVICE_PORT}
      - docktail.service.service-port=443
    healthcheck:
      test: ["CMD", "pgrep", "-f", "app.jar"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: always
